[project]
name = "ai-hard-human-easy-problems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.36.1",
    "pytest>=9.0.2",
    "sympy>=1.14.0",
    "typer>=0.21.0",
]
